config/routes.rb
Rails.application.routes.draw do
  resources :commodities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :rates do
    collection { post :import}

  end

  resources :carrier_types do
    collection { post :import}
  end
  resources :carriers do
    collection  { post :import}
  end
  resources :ports do
    collection { post :import}
  end
  resources :countries do
    collection { post :import}

  end
  resources :unit_of_measures do
    collection { post :import}
  end
  resources :shipment_categories do
    collection { post :import}
  end
  resources :shipment_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "pages#index", page: "index"
  # get "/pages/:page" => "pages#index"
  get "/pages/documentation", page: "documentation"
  get "/pages/import", page: "import"
  get "/pages/restricted_access", page: "restricted_access"

end

app/models/unit_of_measure.rb
class UnitOfMeasure < ApplicationRecord
  has_many :rates

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      UnitOfMeasure.create! row.to_hash
    end
  end
end

app/controllers/unit_of_measures_controller.rb
class UnitOfMeasuresController < ApplicationController
  before_action :set_unit_of_measure, only: [:show, :edit, :update, :destroy]

  # GET /unit_of_measures
  # GET /unit_of_measures.json
  def index
    @unit_of_measures = UnitOfMeasure.all
  end

  # GET /unit_of_measures/1
  # GET /unit_of_measures/1.json
  def show
  end

  # GET /unit_of_measures/new
  def new
    @unit_of_measure = UnitOfMeasure.new
  end

  # GET /unit_of_measures/1/edit
  def edit
  end

  # POST /unit_of_measures
  # POST /unit_of_measures.json
  def create
    @unit_of_measure = UnitOfMeasure.new(unit_of_measure_params)

    respond_to do |format|
      if @unit_of_measure.save
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully created.' }
        format.json { render :show, status: :created, location: @unit_of_measure }
      else
        format.html { render :new }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_of_measures/1
  # PATCH/PUT /unit_of_measures/1.json
  def update
    respond_to do |format|
      if @unit_of_measure.update(unit_of_measure_params)
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit_of_measure }
      else
        format.html { render :edit }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_of_measures/1
  # DELETE /unit_of_measures/1.json
  def destroy
    @unit_of_measure.destroy
    respond_to do |format|
      format.html { redirect_to unit_of_measures_url, notice: 'Unit of measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    UnitOfMeasure.import(params[:file])
    redirect_to unit_of_measures_path, notice: "Units of Measure Imported Successfully!"
    #code
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_of_measure
      @unit_of_measure = UnitOfMeasure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_of_measure_params
      params.require(:unit_of_measure).permit(:name, :shipment_category_id)
    end
end

app/helpers/unit_of_measures_helper.rb
module UnitOfMeasuresHelper
end

app/views/unit_of_measures/_form.html.erb
<%= form_for(unit_of_measure) do |f| %>
  <% if unit_of_measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit_of_measure.errors.count, "error") %> prohibited this unit_of_measure from being saved:</h2>

      <ul>
      <% unit_of_measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_of_measures/edit.html.erb
<h1>Editing Unit Of Measure</h1>

<%= render 'form', unit_of_measure: @unit_of_measure %>

<%= link_to 'Show', @unit_of_measure %> |
<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unit Of Measures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unit_of_measures.each do |unit_of_measure| %>
      <tr>
        <td><%= unit_of_measure.name %></td>
        <td><%= link_to 'Show', unit_of_measure %></td>
        <td><%= link_to 'Edit', edit_unit_of_measure_path(unit_of_measure) %></td>
        <td><%= link_to 'Destroy', unit_of_measure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit Of Measure', new_unit_of_measure_path %>

app/views/unit_of_measures/new.html.erb
<h1>New Unit Of Measure</h1>

<%= render 'form', unit_of_measure: @unit_of_measure %>

<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit_of_measure.name %>
</p>


<%= link_to 'Edit', edit_unit_of_measure_path(@unit_of_measure) %> |
<%= link_to 'Back', unit_of_measures_path %>