config/routes.rb
Rails.application.routes.draw do
  resources :commodities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :rates do
    collection { post :import}

  end

  resources :carrier_types do
    collection { post :import}
  end
  resources :carriers do
    collection  { post :import}
  end
  resources :ports do
    collection { post :import}
  end
  resources :countries do
    collection { post :import}

  end
  resources :unit_of_measures do
    collection { post :import}
  end
  resources :shipment_categories do
    collection { post :import}
  end
  resources :shipment_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "pages#index", page: "index"
  # get "/pages/:page" => "pages#index"
  get "/pages/documentation", page: "documentation"
  get "/pages/import", page: "import"
  get "/pages/restricted_access", page: "restricted_access"

end

app/controllers/shipment_types_controller.rb
class ShipmentTypesController < ApplicationController
  before_action :set_shipment_type, only: [:show, :edit, :update, :destroy]

  # GET /shipment_types
  # GET /shipment_types.json
  def index
    @shipment_types = ShipmentType.all
  end

  # GET /shipment_types/1
  # GET /shipment_types/1.json
  def show
  end

  # GET /shipment_types/new
  def new
    @shipment_type = ShipmentType.new
  end

  # GET /shipment_types/1/edit
  def edit
  end

  # POST /shipment_types
  # POST /shipment_types.json
  def create
    @shipment_type = ShipmentType.new(shipment_type_params)

    respond_to do |format|
      if @shipment_type.save
        format.html { redirect_to @shipment_type, notice: 'Shipment type was successfully created.' }
        format.json { render :show, status: :created, location: @shipment_type }
      else
        format.html { render :new }
        format.json { render json: @shipment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipment_types/1
  # PATCH/PUT /shipment_types/1.json
  def update
    respond_to do |format|
      if @shipment_type.update(shipment_type_params)
        format.html { redirect_to @shipment_type, notice: 'Shipment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment_type }
      else
        format.html { render :edit }
        format.json { render json: @shipment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipment_types/1
  # DELETE /shipment_types/1.json
  def destroy
    @shipment_type.destroy
    respond_to do |format|
      format.html { redirect_to shipment_types_url, notice: 'Shipment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment_type
      @shipment_type = ShipmentType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_type_params
      params.require(:shipment_type).permit(:name)
    end
end

app/helpers/shipment_types_helper.rb
module ShipmentTypesHelper
end

app/views/shipment_types/_form.html.erb
<%= form_for(shipment_type) do |f| %>
  <% if shipment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment_type.errors.count, "error") %> prohibited this shipment_type from being saved:</h2>

      <ul>
      <% shipment_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipment_types/edit.html.erb
<h1>Editing Shipment Type</h1>

<%= render 'form', shipment_type: @shipment_type %>

<%= link_to 'Show', @shipment_type %> |
<%= link_to 'Back', shipment_types_path %>

app/views/shipment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shipment Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shipment_types.each do |shipment_type| %>
      <tr>
        <td><%= shipment_type.name %></td>
        <td><%= link_to 'Show', shipment_type %></td>
        <td><%= link_to 'Edit', edit_shipment_type_path(shipment_type) %></td>
        <td><%= link_to 'Destroy', shipment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shipment Type', new_shipment_type_path %>

app/views/shipment_types/new.html.erb
<h1>New Shipment Type</h1>

<%= render 'form', shipment_type: @shipment_type %>

<%= link_to 'Back', shipment_types_path %>

app/views/shipment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shipment_type.name %>
</p>

<%= link_to 'Edit', edit_shipment_type_path(@shipment_type) %> |
<%= link_to 'Back', shipment_types_path %>