config/routes.rb
Rails.application.routes.draw do
  resources :commodities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :rates do
    collection { post :import}

  end

  resources :carrier_types do
    collection { post :import}
  end
  resources :carriers do
    collection  { post :import}
  end
  resources :ports do
    collection { post :import}
  end
  resources :countries do
    collection { post :import}

  end
  resources :unit_of_measures do
    collection { post :import}
  end
  resources :shipment_categories do
    collection { post :import}
  end
  resources :shipment_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "pages#index", page: "index"
  # get "/pages/:page" => "pages#index"
  get "/pages/documentation", page: "documentation"
  get "/pages/import", page: "import"
  get "/pages/restricted_access", page: "restricted_access"

end

app/views/pages/documentation.html.erb
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <h1>Documentation</h1>
                <%= column_chart Rate.group_by_day(:created_at).count(@rates), label: "Rates Added", title: "Rates Added per Day"  %>

            </div>
        </div>
    </div>
</section>

app/views/pages/import.html.erb
<section>
    <container>
        <row>
          <div class="col-xs-12">
            <h1>User this page to import CSV Files</h1>
          </div>
            <div class="col-xs-12">
                <div id="no-more-tables">
                    <table class="table table-bordered table-striped table-condensed cf">
                        <thead class="cf">
                            <tr></tr>
                        </thead>
                        <tbody class="cf">
                            <tr>
                                <td>Rates</td>
                                <td><%= form_tag import_rates_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Carriers</td>
                                <td><%= form_tag import_carriers_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Countries</td>
                                <td><%= form_tag import_countries_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Ports</td>
                                <td><%= form_tag import_ports_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Carrier Types</td>
                                <td><%= form_tag import_carrier_types_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Shipment Categories</td>
                                <td><%= form_tag import_shipment_categories_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                            <tr>
                                <td>Units of Measure</td>
                                <td><%= form_tag import_unit_of_measures_path, multipart: true do %>
                                    <%= file_field_tag :file %>
                                <%= submit_tag "Import ", class: "btn btn-success" %>
                                    <% end %></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </row>
    </container>
</section>

app/views/pages/index.html.erb
<section class="splash home-cover">
    <div class="container text-center">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="intro-title">Getting rates, the easy way.</h1>
            </div>
        </div>
    </div>
</section>

<!-- <section class="overview">
    <div class="container">
        <div>
            <%= image_tag 'focus.png' %>
            <h2>Accu<color style="color: #fbc93d">rate</color>
            </h2>
            <p>There is nothing worse than discovering your cost is inccurate. We'll make sure your data is active and up-to-date.</p>
        </div>
        <div>
            <%= image_tag 'startup.png' %>
            <h2>Illust<color style="color: #fbc93d">rate</color>
            </h2>
            <p>Presented elegantly with top-tier functionality and streamline processing in mind.</p>
        </div>
        <div>
            <%= image_tag 'coding.png' %>
            <h2>Gene<color style="color: #fbc93d">rate</color>
            </h2>
            <p>Provides flexibility for report customization and multi-conditional queries.</p>
        </div>
    </div>
</section> -->

<section class="feature bluebg">
    <div class="container" style="padding-bottom: 25px">
        <%= image_tag 'iphone-device-mock.png' %>
        <div>
            <h1>Easy Means Easy</h1>
            <ul>
                <li>
                    <%= fa_icon "map-marker"%>
                    <h3>Rates anywhere.</h3>
                    <p>Need rates on the go? All the info you need, in your pocket.</p>

                </li>
                <li>
                    <i class="fa fa-html5"></i>
                    <h3>Simple and Goal Driven</h3>
                    <p>Clean interface allows you to pick your origin and destination. That could be all you need!</p>
                </li>
                <li>
                    <%= fa_icon "paper-plane-o" %>
                    <h3>Fast and Light</h3>
                    <p>Delivering the results you want, no matter the size. Fast.</p>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="feature greybg">
    <div class="container">
        <%= image_tag 'macbook-pro.png' %>
        <div>
            <h1>Easy but Powerful.</h1>
            <p>Rate Cellar is a modular and extendable web-application created to facilitate your logistics quoting process.</p>
            <ul>
                <li>
                    <%= fa_icon "line-chart" %>
                    <h3>History and Forecast</h3>
                    <p>Keep track of past and present cost, allowing you to forecast for upcoming bids.</p>
                </li>
                <li>
                    <%= fa_icon "sliders" %>
                    <h3>Customizable</h3>
                    <p>Easily customize results, to fit your needs and routines.</p>
                </li>
                <li>
                    <%= fa_icon "shield" %>
                    <h3>Secure</h3>
                    <p>Safely maintain and store you rate information from all of your vendors.</p>
                </li>
            </ul>
        </div>
    </div>
</section>

<section class="cta">
    <div class="container">
        <h1>Research Less, Move More.</h1>
        <h2>Instead of wasting time researching rates, use that time to win more bids.</h2>

    </a>
</div>
</section>

<footer class="footer">
    <div class="container">
        <div class="copyright">
            <div class="col-xs-6">
                <p>Powered by:
                    <%= link_to  image_tag("logo.png"),  "http://www.kinetixrelo.com", target: "_blank" %>
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/pages/restricted_access.html.erb
<section class="splash restricted-access-cover">
    <div class="container text-center">
        <div class="row">
            <div class="col-xs-12">
                <h1 class="intro-title" style="color: white">Sorry! Admin Access Only!</h1>
            </div>
        </div>
    </div>
</section>