config/routes.rb
Rails.application.routes.draw do
  resources :commodities
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :rates do
    collection { post :import}

  end

  resources :carrier_types do
    collection { post :import}
  end
  resources :carriers do
    collection  { post :import}
  end
  resources :ports do
    collection { post :import}
  end
  resources :countries do
    collection { post :import}

  end
  resources :unit_of_measures do
    collection { post :import}
  end
  resources :shipment_categories do
    collection { post :import}
  end
  resources :shipment_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root "pages#index", page: "index"
  # get "/pages/:page" => "pages#index"
  get "/pages/documentation", page: "documentation"
  get "/pages/import", page: "import"
  get "/pages/restricted_access", page: "restricted_access"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <div class="copyright">
            <div class="col-xs-6">
                <p>Powered by:
                    <%= link_to  image_tag("logo.png"),  "http://www.kinetixrelo.com", target: "_blank" %>
                </p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "KRATES", root_path , class: 'navbar-brand '%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li class="<%= 'active' if current_page?(root_path) %> "><%= link_to "Home", root_path %></li>
                <li class="<%= 'active' if current_page?(rates_path) %>"><%= link_to "Rates", rates_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in?%>
              <li class="<%= 'active' if current_page?(pages_documentation_path) %>"><%= link_to "Documentation", pages_documentation_path %></li>
              <% if current_user.admin?%>
              <li class="<%= 'active' if current_page?(pages_import_path) %>"><%= link_to "Import", pages_import_path %></li>
              <li><%= link_to "Admin Dashboard", rails_admin_path %></li>
              <% end %>
              <li><%= link_to "Edit User", edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li class="<%= 'active' if current_page?(new_user_registration_path) %> "><%= link_to "Sign Up", new_user_registration_path %></li>
              <li class="<%= 'active' if current_page?(new_user_session_path) %> "><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
            </ul>
        </div>
    </div>
    <!-- Brand and toggle get grouped for better mobile display -->

    <!-- /.navbar-collapse -->
    <!-- /.container-fluid -->
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate Cellar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
<%= render "layouts/header" %>

  <%= yield %>



  </body>
</html>